### ISSUE TITLE
d is normally for deletion

### ISSUE THREAD

**Issue by laoshaw** [kitplummer/clikan#10]
for display I would set it as default,  instead of needing a "d" option,  as "d" is almost always used for "deletion" shortcut elsewhere, just a suggestion.

**Comment by kitplummer** [comment]
that makes a ton of sense for sure.  thanks for the suggestion!

**Comment by kitplummer** [comment]
Turns out that the default command is a challenge.  Can def entertain the need to change "d" to "s" for show, and move "remove" to "delete".  Semantics I know, and valid.  Will keep this open and see if anyone else chimes in.  I suppose I've just gotten used to it.

**Comment by kitplummer** [comment]
New version out: https://pypi.org/project/clikan/

`d` for delete.  `s` for show.
