### ISSUE TITLE
Need help/documentation to run the test suite

### ISSUE THREAD

**Issue by gbnaidu** [kitplummer/clikan#15]
Hi,
Thanks for this tool. I am thinking of taking a deeper look and possibly contribute.

Could you add some instructions on how to run the test suite provided with this package?

Thanks

**Comment by kitplummer** [comment]
I've updated the README.md in the `develop` branch.  But the short is:

`pytest clikan_test.py` will run the tests.  Note: it'll fail tests if you have anything in your `~/.clikan.dat` file - meant to be run from CI/CD.  But that might be something helpful, is point the test runner at a different data file.

Thanks for the interest, and looking to contribute.
