### ISSUE TITLE
[Enhancement] Add option for default "show"

### ISSUE THREAD

**Issue by ishigoya** [kitplummer/clikan#19]
Hey, thanks for the great project!

I'd just like to suggest an enhancement: an option in the config that allows "show" to be the default command. So running `clikan` on the command line would result in `clikan show` being executed.

I'd be happy to have a go at doing this and submitting a pull request.

**Comment by kitplummer** [comment]
This feature had been discussed before.  Making it a configuration option
makes sense to me.  Will look for the PR.

**Comment by dmtregrv** [comment]
If you use at linux maschine possible fix to use alias.

**Comment by kitplummer** [comment]
Just made it the default behavior - as it makes the most sense.  Just released.
