### ISSUE TITLE
add support for moving yaml file

### ISSUE THREAD

**Issue by blakat360** [kitplummer/clikan#29]
It would be good to have the yaml file in .config on linux systems.

**Comment by kitplummer** [comment]
I agree.  Sorry for taking so long for getting to you on this.  I think this is an easy fix - and I want to make it something that can be overridden with a CLI flag.

**Comment by kitplummer** [comment]
So...it's funny how you forget things when you've not looked at them for a while.  The easy fix for this is to set `CLIKAN_HOME` to `~/.config` in your appropriate shell configuration.  The `.yaml` can be anywhere, but you will need to tell clikan where it is.
