### ISSUE TITLE
The version in developer branch is 2.0.1 or 2.0.0

### ISSUE THREAD

**Issue by davidventasmarin** [kitplummer/clikan#34]
When execute test, it fails me this function "test_command_version" I obtain the follow mistake.

#########################################################################################
def test_command_version():
        version_file = open(os.path.join('./', 'VERSION'))
        version = version_file.read().strip()

        runner = CliRunner()
        result = runner.invoke(clikan, ["--version"])
        assert result.exit_code == 0
>       assert 'clikan, version {}'.format(version) in result.output
E       AssertionError: assert 'clikan, version 0.2.1' in 'clikan, version 0.2.0\n'
E        +  where 'clikan, version 0.2.1' = <built-in method format of str object at 0x00000239651F2800>('0.2.1')
E        +    where <built-in method format of str object at 0x00000239651F2800> = 'clikan, version {}'.format
E        +  and   'clikan, version 0.2.0\n' = <Result okay>.output
#########################################################################################

I put clikan --version and show me 2.0.0 version, but in VERSION file put 2.0.1.
The test it's easy to correct it. But I need know the correct version, in case I have made a mistake in the download or in the branch. 

Thanks for your project.

**Comment by kitplummer** [comment]
So...not always super optimal I know, but the tests are actually "functional" tests that verify the CLI.  The tests expect a "clean" environment, where `clikan` has been installed and no config or data files exist.  I'm guessing you have those locally so the tests are failing.  Also, the tests assume you're test the same version of code - and have done the install with `python setup.py install`.  You can see this in the GHA configuration too.

**Comment by kitplummer** [comment]
Closing out...as this is an artifact of a "dev" env thing that we do need to fix, but will track this in a diff ticket.
