### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by jgarte** [kitplummer/clikan#36]
Hi, do these tests fail for anyone else?

```
============================= test session starts ==============================
platform linux -- Python 3.8.2, pytest-5.3.5, py-1.8.1, pluggy-0.13.1 -- /gnu/store/2dqjp4nl4iqkwz0914lq2ch098c1vvli-python-wrapper-3.8.2/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/jgart/clikan/.hypothesis/examples')
rootdir: /home/jgart/clikan
plugins: hypothesis-5.4.1
collecting ... collected 11 items

clikan_test.py::test_command_help PASSED                                 [  9%]
clikan_test.py::test_command_version PASSED                              [ 18%]
clikan_test.py::test_command_configure FAILED                            [ 27%]
clikan_test.py::test_command_configure_existing PASSED                   [ 36%]
clikan_test.py::test_command_a PASSED                                    [ 45%]
clikan_test.py::test_no_command PASSED                                   [ 54%]
clikan_test.py::test_command_s PASSED                                    [ 63%]
clikan_test.py::test_command_show PASSED                                 [ 72%]
clikan_test.py::test_command_not_show PASSED                             [ 81%]
clikan_test.py::test_command_promote PASSED                              [ 90%]
clikan_test.py::test_command_delete PASSED                               [100%]

=================================== FAILURES ===================================
____________________________ test_command_configure ____________________________

    def test_command_configure():
        runner = CliRunner()
        result = runner.invoke(clikan, ["configure"])
        assert result.exit_code == 0
>       assert 'Creating' in result.output
E       AssertionError: assert 'Creating' in 'Config file exists. Do you want to overwrite? [y/N]: \n'
E        +  where 'Config file exists. Do you want to overwrite? [y/N]: \n' = <Result okay>.output

clikan_test.py:30: AssertionError
========================= 1 failed, 10 passed in 0.64s =========================
```

**Comment by davidventasmarin** [comment]
7 fails for me

**Comment by kitplummer** [comment]
Will take a look at this today.

**Comment by kitplummer** [comment]
Just answered this in another issue: #34

Am guessing you already have the `~/.clikan.yaml` and `~/.clikan.dat` files locally, which are causing the test to fail.  I've been meaning to resolve this for some time.  Would love it if somebody would take a look at being able to set a test context configuration that looks for the config files either somewhere else or can do some quick moving to allow for developers who have it legitimately installed to run the functional tests.

**Comment by davidventasmarin** [comment]
an idea could be than test enviroment read from a local file. For production or working enviroment you read system variable, and test enviroment with local file throught a path. For example:

    -git
        -clikan
            *clikan.yaml
            *clikan.dat

I will try to solve it with this premise

**Comment by davidventasmarin** [comment]
> Just answered this in another issue: #34
> 
> Am guessing you already have the `~/.clikan.yaml` and `~/.clikan.dat` files locally, which are causing the test to fail. I've been meaning to resolve this for some time. Would love it if somebody would take a look at being able to set a test context configuration that looks for the config files either somewhere else or can do some quick moving to allow for developers who have it legitimately installed to run the functional tests.

It's correct, I delete all information, and I have pass the test again and pass all the test.

PS C:\Users\david\Documents\proyectos\git\clikan> pytest .\clikan_test.py
=========================================================================================================== test session starts ============================================================================================================
platform win32 -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: C:\Users\david\Documents\proyectos\git\clikan
collected 11 items

clikan_test.py ...........                                                                                                                                                                                                            [100%]

============================================================================================================ 11 passed in 0.18s ============================================================================================================
