### ISSUE TITLE
Automatically show after modification

### ISSUE THREAD

**Issue by sethcenterbar** [kitplummer/clikan#46]
Love the project! 

I find that after every modification command I run (add, delete, promote, regress), I inevitably run `clikan show` after.  What would you think about a configuration value that allows you to automatically run show after modifications? I'd like to contribute that to the project if you think it would be useful to others.

**Comment by kitplummer** [comment]
@sethcenterbar - did you want to take a whack at implementing the functionality?  if so, don't look at the https://github.com/kitplummer/clikan/tree/repaint branch. :D  if not, feel free to pull down and run it.  i've finally got a good enough reason to add some support for better testing the config variations.  This one's pretty simple - just add `repaint: true` to your `clikan.yaml` and it should behave as you'd described.
