### ISSUE TITLE
Mastodon account for this project

### ISSUE THREAD

**Issue by Lukas2112** [kitplummer/clikan#47]
Would a Mastodon account for this project be possible?

**Comment by kitplummer** [comment]
What would the point be, what problem does that solve?

**Comment by Lukas2112** [comment]
Specifically, my idea would be to break it down into three points: 

- Sharing project information in general
- Sharing project announcements 
- Interaction with the Fediverse community (example could be polls on considered features from the engine room)

I don't know if there is already a project that could make this easier with project releases, but I'm sure it would be easy to realise.
