### ISSUE TITLE
Command abbreviations

### ISSUE THREAD

**Issue by OdayMansour** [kitplummer/clikan#57]
Hi,
What do you think about putting in abbreviations for commands?

```
clikan a "Buy toilet paper" # a for add
clikan p 1 # p for promote
clikan d 1 # d for delete
```

Again, I can write this. I'm not trying to be pushy, I'm only checking if you think it's a good idea.

**Comment by Dino0Z** [comment]
Hi,

Abbreviations/aliases already exist för adding, promoting and deleting tasks (same as your suggestion).

**Comment by OdayMansour** [comment]
Oh oops, sorry about that. Thanks for clearing that up!
